default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5
  username: ubuntu
  password: 4225e1492

development:
  <<: *default
  database: hellowolrd_development

test:
  <<: *default
  database: hellowolrd_test

production:
  <<: *default
  encoding: unicode
  database: hellowolrd